[package]
name = "prml-attestation"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.5.4", default-features = false, features = ["derive"] }
primitives = { package = "substrate-primitives", path = "../../../plug-blockchain/core/primitives", default-features = false }
runtime-primitives = { package = "sr-primitives", path = "../../../plug-blockchain/core/sr-primitives", default-features = false }
sr-std = { path = "../../../plug-blockchain/core/sr-std", default-features = false }
sr-io = { path = "../../../plug-blockchain/core/sr-io", default-features = false }
srml-support = { path = "../../../plug-blockchain/srml/support", default-features = false }
srml-system = { path = "../../../plug-blockchain/srml/system", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"primitives/std",
	"runtime-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-system/std",
]
