[package]
name = "cennznet-primitives"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
runtime-io = { package = "sr-io", path = "../../plug-blockchain/core/sr-io", default-features = false }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.5.4", default-features = false, features = ["derive"] }

primitives = { package = "substrate-primitives", path = "../../plug-blockchain/core/primitives", default-features = false }
rstd = { package = "sr-std", path = "../../plug-blockchain/core/sr-std", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../plug-blockchain/core/sr-primitives", default-features = false }
support = { package="srml-support", path = "../../plug-blockchain/srml/support", default-features = false }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"primitives/std",
	"runtime-io/std",
	"rstd/std",
	"runtime_primitives/std",
	"serde_derive",
	"serde/std",
	"support/std",
]
