[package]
name = "cennznet-cli"
version = "1.2.0"
authors = ["Centrality Developers <support@centrality.ai>"]
description = "CENNZnet node implementation in Rust."
build = "build.rs"
edition = "2018"
license = "GPL-3.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
serde = { version = "1.0.102", features = ["derive"] }
structopt = "0.3.8"

sc-authority-discovery = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-chain-spec = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-cli = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain", features = ["wasmtime"] }
sp-core = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-executor = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain", features = ["wasmtime"] }
sc-keystore = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-service = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain", features = ["wasmtime"] }
sp-inherents = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-transaction-pool = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-transaction-pool = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-authority-discovery = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-consensus-babe = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain", features = ["test-helpers"] }
sp-consensus-babe = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-consensus = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-consensus-epochs = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-consensus = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-network = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-finality-grandpa = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-finality-grandpa = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-client-api = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-runtime = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }

# These dependencies are used for the node RPCs
jsonrpc-core = "15.0.0"
pallet-transaction-payment-rpc = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-rpc = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-api = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-rpc-api = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-blockchain = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-block-builder = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-basic-authorship = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
substrate-frame-rpc-system = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-consensus-babe-rpc = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-finality-grandpa-rpc = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
frame-benchmarking-cli = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }

# cennznet dependencies
cennznet-primitives = { path = "../primitives" }
cennznet-runtime = { path = "../runtime" }
# cennznet custom RPCs
crml-cennzx-rpc = { path = "../crml/cennzx/rpc" }
prml-generic-asset-rpc = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
prml-generic-asset = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }

pallet-im-online = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "hotfix/cennznet-1.2.2" }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", features = ["derive"] }
sp-finality-tracker = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-keyring = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sp-timestamp = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
sc-service-test = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
frame-system = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }
crml-transaction-payment = { path = "../crml/transaction-payment" }
tempfile = "3.1.0"

[build-dependencies]
substrate-build-script-utils = { branch = "hotfix/cennznet-1.2.2", git = "https://github.com/plugblockchain/plug-blockchain" }

[features]
default = []
runtime-benchmarks = [
	"cennznet-runtime/runtime-benchmarks",
]
