[package]
name = "prml-fees"
version = "0.1.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
parity-codec = { version = "3.5.4", default-features = false }
primitives = { package = "substrate-primitives", path = "../../../plug-blockchain/core/primitives", default-features = false }
rstd = { package="sr-std", path = "../../../plug-blockchain/core/sr-std", default-features = false }
runtime_io = { package="sr-io", path = "../../../plug-blockchain/core/sr-io", default-features = false }
runtime_primitives = { package="sr-primitives", path = "../../../plug-blockchain/core/sr-primitives", default-features = false }
support = { package="srml-support", path = "../../../plug-blockchain/srml/support", default-features = false }
system = { package="srml-system", path = "../../../plug-blockchain/srml/system", default-features = false }

[dev-dependencies]
generic-asset = { package="prml-generic-asset", path = "../generic-asset" }

[features]
default = ["std"]
std = [
	"serde",
	"parity-codec/std",
	"primitives/std",
	"rstd/std",
	"runtime_io/std",
	"runtime_primitives/std",
	"support/std",
	"system/std",
]
